In [3]:
from sympy import Matrix

A = Matrix([[2, 1, -1], [-3, -1, 2], [-2, 1, 2]])
A.rref()  # Reduce la matriz a su forma escalonada reducida


(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [ ]:
# Reimportar librerías después del reinicio
from sympy import Matrix, symbols, init_printing

# Inicializar impresión bonita
init_printing()

# Definir las variables y la matriz aumentada
x, y, z = symbols('x y z')
A = Matrix([
    [2, 1, -1, 8],   # Ecuación 1: 2x + y - z = 8
    [-3, -1, 2, -11], # Ecuación 2: -3x - y + 2z = -11
    [-2, 1, 2, -3]   # Ecuación 3: -2x + y + 2z = -3
])

# Mostrar la matriz aumentada original
print("Matriz aumentada inicial:")
A

# Paso 1: Llevar la matriz a forma escalonada reducida
rref_A, pivots = A.rref()  # Forma escalonada reducida y pivotes
rref_A


In [24]:
import numpy as np

def eliminacion_gaussiana(A):
    if not isinstance(A, np.ndarray):
        A = np.array(A)
    A = np.round(A, 2)
    assert A.shape[0] == A.shape[1] - 1, "La matriz A debe ser de tama\u00f1o n-by-(n+1)."
    n = A.shape[0]

    print("Estado inicial de la matriz:")
    print(A)
    
    for i in range(0, n - 1):
        p = None
        for pi in range(i, n):
            if A[pi, i] == 0:
                continue

            if p is None:
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            raise ValueError("No existe soluci\u00f3n \u00fanica.")

        if p != i:
            print(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        for j in range(i + 1, n):
            m = round(A[j, i] / A[i, i], 2)
            A[j, i:] = np.round(A[j, i:] - m * A[i, i:], 2)

        print(f"Estado de la matriz tras la eliminaci\u00f3n en la columna {i}:")
        print(A)

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe soluci\u00f3n \u00fanica.")

    solucion = np.zeros(n)
    solucion[n - 1] = round(A[n - 1, n] / A[n - 1, n - 1], 2)

    for i in range(n - 2, -1, -1):
        suma = 0
        for j in range(i + 1, n):
            suma += A[i, j] * solucion[j]
        solucion[i] = round((A[i, n] - suma) / A[i, i], 2)

    return solucion

A = np.array([
    [-1,  4,  1,  8],
    [5/3, 2/3, 2/3, 1],
    [2,   1,   4,  11]
], dtype=float)

solucion = eliminacion_gaussiana(A)
print("\nSoluci\u00f3n del sistema:")
print(solucion)


Estado inicial de la matriz:
[[-1.    4.    1.    8.  ]
 [ 1.67  0.67  0.67  1.  ]
 [ 2.    1.    4.   11.  ]]
Estado de la matriz tras la eliminación en la columna 0:
[[-1.    4.    1.    8.  ]
 [ 0.    7.35  2.34 14.36]
 [ 0.    9.    6.   27.  ]]
Estado de la matriz tras la eliminación en la columna 1:
[[-1.    4.    1.    8.  ]
 [ 0.    7.35  2.34 14.36]
 [ 0.    0.03  3.15  9.48]]

Solución del sistema:
[-0.99  1.    3.01]


In [16]:
import numpy as np

# Función  eliminación gaussiana
def eliminacion_gaussiana(A):
    if not isinstance(A, np.ndarray):
        A = np.array(A)
    assert A.shape[0] == A.shape[1] - 1, "La matriz A debe ser de tamaño n-by-(n+1)."
    n = A.shape[0]

    for i in range(0, n - 1):
        p = None
        for pi in range(i, n):
            if A[pi, i] == 0:
                continue

            if p is None:
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            raise ValueError("No existe solución única.")

        if p != i:
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        for j in range(i + 1, n):
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    solucion = np.zeros(n)
    solucion[n - 1] = A[n - 1, n] / A[n - 1, n - 1]

    for i in range(n - 2, -1, -1):
        suma = 0
        for j in range(i + 1, n):
            suma += A[i, j] * solucion[j]
        solucion[i] = (A[i, n] - suma) / A[i, i]

    return np.round(solucion, 2)

# Sistema a
A_a = np.array([
    [-1, 4, 1, 8],
    [5/3, 1/3, 2/3, 1],
    [2, 1, 4, 11]
])


# Resolucion del primer sistema
sol_a = eliminacion_gaussiana(A_a)
print(f"Solución del sistema a: {sol_a}")


Solución del sistema a: [-0.76  1.1   2.86]


In [20]:
np.round(5/3, 2)

In [ ]:
def eliminacion_gaussianacompletaconround2(A):
    init_printing()
    if not isinstance(A, np.ndarray):
        A = np.array(A)
    A = np.round(A, 2)
    assert A.shape[0] == A.shape[1] - 1, "La matriz A debe ser de tamaño n-by-(n+1)."
    n = A.shape[0]

    print("Estado inicial de la matriz:")
    print(A)
    
    for i in range(0, n - 1):
        p = None
        for pi in range(i, n):
            if A[pi, i] == 0:
                continue

            if p is None:
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            raise ValueError("No existe solución única.")

        if p != i:
            print(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux
            print(f"Estado de la matriz tras el intercambio:")
            print(A)

        for j in range(i + 1, n):
            m = round(A[j, i] / A[i, i], 2)
            A[j, i:] = np.round(A[j, i:] - m * A[i, i:], 2)

        print(f"Estado de la matriz tras la eliminación en la columna {i}:")
        print(A)

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    solucion = np.zeros(n)
    solucion[n - 1] = round(A[n - 1, n] / A[n - 1, n - 1], 2)

    for i in range(n - 2, -1, -1):
        suma = 0
        for j in range(i + 1, n):
            suma += A[i, j] * solucion[j]
        solucion[i] = round((A[i, n] - suma) / A[i, i], 2)

    return solucion

In [7]:
def eliminacion_gaussiana_32bits(A):
    A = A.astype(np.float32)
    
    n = A.shape[0]
    print("Estado inicial de la matriz:")
    print(A)

    for i in range(0, n - 1):
        if A[i, i] == 0:
            raise ValueError("El pivote es cero. El sistema puede no tener solución única.")

        for j in range(i + 1, n):
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

        print(f"Estado de la matriz tras la eliminación en la columna {i}:")
        print(A)

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    solucion = np.zeros(n, dtype=np.float32)
    solucion[n - 1] = A[n - 1, n] / A[n - 1, n - 1]

    for i in range(n - 2, -1, -1):
        suma = np.sum(A[i, i+1:n] * solucion[i+1:n])
        solucion[i] = (A[i, n] - suma) / A[i, i]

    return solucion

In [2]:
def gauss_jordan(A):
    if not isinstance(A, np.ndarray):
        A = np.array(A)
    assert A.shape[0] == A.shape[1] - 1, "La matriz A debe ser de tamaño n-by-(n+1)."
    n = A.shape[0]

    print("Estado inicial de la matriz:")
    print(A)

    for i in range(0, n):
        # Encontrar el pivote
        p = None
        for pi in range(i, n):
            if A[pi, i] == 0:
                continue

            if p is None:
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            raise ValueError("No existe solución única.")

        # Intercambiar filas si es necesario
        if p != i:
            print(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux
            print(f"Estado de la matriz tras el intercambio:")
            print(A)

        # Normalizar la fila del pivote
        A[i, :] = A[i, :] / A[i, i]

        # Eliminar todas las entradas en la columna del pivote (hacia arriba y hacia abajo)
        for j in range(n):
            if j != i:
                m = A[j, i]
                A[j, :] = A[j, :] - m * A[i, :]

        print(f"Estado de la matriz tras la eliminación en la columna {i}:")
        print(A)

    solucion = A[:, -1]
    return solucion